/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package flowtrac.core.model.issue;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import flowtrac.core.model.Item;
import flowtrac.core.model.user.User;

/**
 * @author Markus Staeuble
 *
 */
@Entity
public class Issue implements Item {

	public User getUser() {
		return createdBy;
	}

	public void setUser(User user) {
		this.createdBy = user;
	}

	/**
	 * Generated by eclipse. 
	 */
	private static final long serialVersionUID = 5711325923341961421L;
	
	private String name;
	private String description;
	private String severity;
	private String version;
	private User createdBy;
	private Long id;
	private Date fixingDate;
	private Date lastModifed;
	private Date creationDate;
	

	/**
	 * @see flowtrac.core.model.issue.Issue#getFixingDate()
	 */
	public Date getFixingDate() {
		return this.fixingDate;
	}

	/**
	 * @see flowtrac.core.model.issue.Issue#getId()
	 */
	@Id
	@GeneratedValue
	public Long getId() {		
		return this.id;
	}

	/**
	 * @see flowtrac.core.model.issue.Issue#getName()
	 */
	public String getName() {
		return this.name;
	}


	public String getSeverity() {
		return severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	/**
	 * @see flowtrac.core.model.issue.Issue#setName(java.lang.String)
	 */
	public void setName(String name) {
		this.name = name;
	}


	/**
	 * @see flowtrac.core.model.issue.Issue#setId(long)
	 */
	
	public void setId(long id) {
		this.id = id;
		
	}

	/**
	 * @see flowtrac.core.model.issue.Issue#setFixingDate(java.util.Date)
	 */
	
	public void setFixingDate(Date fixingDate) {
		this.fixingDate = fixingDate;
		
	}

	/* (non-Javadoc)
	 * @see flowtrac.core.model.issue.ItemInformation#getCreatedBy()
	 */
	
	public User getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * @see flowtrac.core.model.issue.ItemInformation#getCreationDate()
	 */
	
	public Date getCreationDate() {
		return this.creationDate;
	}

	/**
	 * @see flowtrac.core.model.issue.ItemInformation#getLastModified()
	 */
	
	public Date getLastModified() {
		return this.lastModifed;
	}

	/* (non-Javadoc)
	 * @see flowtrac.core.model.issue.ItemInformation#getLastModifiedBy()
	 */
	
	public User getLastModifiedBy() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see flowtrac.core.model.issue.ItemInformation#setCreatedBy(flowtrac.core.model.user.User)
	 */
	
	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
		
	}

	/**
	 * @see flowtrac.core.model.issue.ItemInformation#setCreationDate(java.util.Date)
	 */
	
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
		
	}

	/**
	 * @see flowtrac.core.model.issue.ItemInformation#setLastModified(java.util.Date)
	 */
	
	public void setLastModified(Date lastModified) {
		this.lastModifed = lastModified;
		
	}

	/* (non-Javadoc)
	 * @see flowtrac.core.model.issue.ItemInformation#setLastModifiedBy(flowtrac.core.model.user.User)
	 */
	
	public void setLastModifiedBy(User lastModfiedBy) {
		// TODO Auto-generated method stub
		
	}

	/**
	 * @see flowtrac.core.model.issue.Issue#getDescription()
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * @see flowtrac.core.model.issue.Issue#setDescription(java.lang.String)
	 */
	public void setDescription(final String description) {
		this.description = description;		
	}
	
	private Type type;
	/**
	 * @return type type of the issue.
	 */
	public Type getType()  {
		return this.type;
	}
	
	public void setType(final Type type)  {
		this.type = type;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}
	
	
}
